//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_1.Context
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class empleado
    {
        public int idEmp { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public Nullable<int> idcomp { get; set; }

        public IEnumerable<SelectListItem> ListadoComp { get; set; }
    }
}
